## Train Test Frameworks

The following exercise is to practice the syntax of the various functions from sklearn that split data into train and test sets. The goal of this exercise is to get familiar with these different splitting methods before engaging with the more complex activities at the end of the day. 

In [1]:
# import numpy
import numpy as np

In [2]:
X = np.random.normal(0,1,20).reshape(10,2)
y = np.random.normal(0,1,10)

* print X

In [3]:
print(X)

[[-0.05083452  0.83550097]
 [ 0.56550504 -0.0491725 ]
 [ 1.06727977  0.32362834]
 [-1.14997188  1.00685908]
 [ 0.94273248 -0.21899477]
 [ 0.37461725 -0.99929735]
 [ 1.41578126  0.74645605]
 [-0.6950902  -0.78186356]
 [-1.06133971  0.24293121]
 [-0.66316842 -0.5242617 ]]


* print y

In [4]:
print(y)

[ 0.94524971 -0.42808399  1.24390734  1.78212551  1.71977111 -0.14108671
  0.13630081 -0.56102418  0.56893278 -0.33246555]


_____________________________
### Holdout split

* import the **train_test_split** function from sklearn

In [5]:
from sklearn.model_selection import train_test_split

* split the data to train set and test set, use a 70:30 ratio or a 80:20 ratio.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

* print X_train

In [7]:
print(X_train)

[[-0.05083452  0.83550097]
 [-0.6950902  -0.78186356]
 [ 1.06727977  0.32362834]
 [-0.66316842 -0.5242617 ]
 [ 0.94273248 -0.21899477]
 [-1.14997188  1.00685908]
 [ 1.41578126  0.74645605]]


* split the data again but now with the parameter shuffle = False

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42, shuffle=False)

* print X_train

In [9]:
print(X_train)

[[-0.05083452  0.83550097]
 [ 0.56550504 -0.0491725 ]
 [ 1.06727977  0.32362834]
 [-1.14997188  1.00685908]
 [ 0.94273248 -0.21899477]
 [ 0.37461725 -0.99929735]
 [ 1.41578126  0.74645605]]


* print the shape of X_train and X_test

In [10]:
X_train.shape

(7, 2)

In [11]:
X_test.shape

(3, 2)

_________________________________
### K-fold split 

* import the **KFold** function from sklearn

In [12]:
from sklearn.model_selection import KFold

* instantiate KFold with k=5

In [13]:
kf = KFold(n_splits=5)

* iterate over train_index and test_index in kf.split(X) and print them

In [14]:
for train_index, test_index in kf.split(X):
    print("Train Index: ", train_index)
    print("Test Index: ", test_index)

Train Index:  [2 3 4 5 6 7 8 9]
Test Index:  [0 1]
Train Index:  [0 1 4 5 6 7 8 9]
Test Index:  [2 3]
Train Index:  [0 1 2 3 6 7 8 9]
Test Index:  [4 5]
Train Index:  [0 1 2 3 4 5 8 9]
Test Index:  [6 7]
Train Index:  [0 1 2 3 4 5 6 7]
Test Index:  [8 9]


* instantiate KFold with k=5 and shuffle=True

In [15]:
kf = KFold(n_splits=5, shuffle=True)

* iterate over train_index and test_index in kf.split(X) and print them

In [16]:
for train_index, test_index in kf.split(X):
    print("Train Index: ", train_index)
    print("Test Index: ", test_index)

Train Index:  [1 2 3 4 6 7 8 9]
Test Index:  [0 5]
Train Index:  [0 1 3 4 5 7 8 9]
Test Index:  [2 6]
Train Index:  [0 1 2 4 5 6 8 9]
Test Index:  [3 7]
Train Index:  [0 1 2 3 5 6 7 9]
Test Index:  [4 8]
Train Index:  [0 2 3 4 5 6 7 8]
Test Index:  [1 9]


_______________________________________
### Leave-One-Out split
This is a similar technique to the Leave-p-out in the previous readings, with p=1. Each observation is used as test set separately.
- This is a popular method for tiny datasets.
- It takes a lot of time with bigger datasets and can lead to overfitting on a final model.

* import the **LeaveOneOut** function from sklearn

In [17]:
from sklearn.model_selection import LeaveOneOut

* instantiate LeaveOneOut

In [18]:
loo = LeaveOneOut()

* iterate over train_index and test_index in loo.split(X) and print them

In [19]:
for train_index, test_index in loo.split(X):
    print("Train Index: ", train_index)
    print("Test Index: ", test_index)

Train Index:  [1 2 3 4 5 6 7 8 9]
Test Index:  [0]
Train Index:  [0 2 3 4 5 6 7 8 9]
Test Index:  [1]
Train Index:  [0 1 3 4 5 6 7 8 9]
Test Index:  [2]
Train Index:  [0 1 2 4 5 6 7 8 9]
Test Index:  [3]
Train Index:  [0 1 2 3 5 6 7 8 9]
Test Index:  [4]
Train Index:  [0 1 2 3 4 6 7 8 9]
Test Index:  [5]
Train Index:  [0 1 2 3 4 5 7 8 9]
Test Index:  [6]
Train Index:  [0 1 2 3 4 5 6 8 9]
Test Index:  [7]
Train Index:  [0 1 2 3 4 5 6 7 9]
Test Index:  [8]
Train Index:  [0 1 2 3 4 5 6 7 8]
Test Index:  [9]


* print the number of splits

In [20]:
print("Number of splits: ", loo.get_n_splits(X))

Number of splits:  10
